name: The First Workflow
on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
        - name: Run Shell Commands
          run: |
            echo "Hello, World!"

        - name: Run Another Command
          run: |
            node -v
            npm -v